In [7]:
# Written by E. Margaret Perkoff
# Imports
import numpy as np
import torch
from transformers import BertTokenizer, BertModel

In [3]:
# Data Loading/Cleaning
def read_file_for_lexicon(filename):
    lexicon = set()
    with open(filename, 'r') as f:
        for line in f:
            for word in line.split():
                lexicon.add(word)
    return lexicon


In [4]:
# Create Lexicon
filepath = "data/dev_langs/Maltese.bible.txt"
lexicon = read_file_for_lexicon(filepath)
len(lexicon)

16016

In [8]:
# bert embeddings
for w in lexicon:
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased')
    input_ids = torch.tensor(tokenizer.encode(w)).unsqueeze(0)  # Batch size 1
    outputs = model(input_ids)
    last_hidden_states = outputs[0]
    print(last_hidden_states)

l
tensor([[[-4.4072e-01, -1.8348e-01, -1.6113e-03,  ..., -6.0134e-02,
          -7.0514e-02,  3.5271e-01],
         [-5.0916e-01, -9.6933e-01,  2.4135e-01,  ...,  2.8366e-04,
           2.3390e-01, -2.1266e-01],
         [ 1.1290e+00,  5.8937e-02, -4.2739e-01,  ...,  3.1706e-01,
          -7.2257e-01, -2.7171e-01]]], grad_fn=<NativeLayerNormBackward>)
is-sħaba
tensor([[[-0.6268,  0.6365, -0.6584,  ...,  0.2501,  0.4530,  0.4518],
         [-0.0906,  0.0985, -0.6542,  ...,  0.0767,  0.7443,  1.2843],
         [-0.0457,  0.3930, -0.4709,  ...,  0.3635,  0.4519,  0.3283],
         ...,
         [ 0.5948,  1.0898,  0.0549,  ...,  0.2529,  0.2524, -0.1980],
         [ 0.2154,  0.5033, -0.9991,  ..., -0.1122, -0.2267, -0.3997],
         [ 0.6474,  0.2395, -0.5125,  ...,  0.2438, -0.8117, -0.2314]]],
       grad_fn=<NativeLayerNormBackward>)
jiġġudikani


KeyboardInterrupt: 

In [18]:
def find_longest_substring(w1, w2):
    substrings = np.zeros((len(w1), len(w2)))
    
    for i in range(1, len(w1)):
        for j in range(1, len(w2)):
            if (w1[i - 1] == w2[j - 1]):
                substrings[i][j] = substrings[i-1][j - 1] + 1
            else:
                substrings[i][j] = 0
    print(substrings)
    max_indices = np.where(substrings == substrings.max())
    
    return max_indices
print(find_longest_substring("aa", "aaa"))
print(find_longest_substring("aba", "aab"))
                

[[0. 0. 0.]
 [0. 1. 1.]]
(array([1, 1]), array([1, 2]))
[[0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]]
(array([1, 1]), array([1, 2]))


In [ ]:

            
def most_common_n_substring(lexicon, ):
    substrings = dict()
    for w in lexicon:
        lexicon.remove(w)
        for y in lexicon:
            longest_substring = find_longest_substring(w, y)
            
        

In [10]:
# Create a character embedding based on letters
def create_word_embedding(lexicon, max_word_size):
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = TFBertModel.from_pretrained('bert-base-uncased')
    input_ids = tf.constant(tokenizer.encode("Hello, my dog is cute"))[None, :]  # Batch size 1
    outputs = model(input_ids)
    last_hidden_states = outputs[0]
    
    size = len(lexicon)
    # Initialize embedding matrix of words x 26
    embedding_matrix = np.chararray((size, max_word_size))
    i = 0
    for w in lexicon:
        char_embedding = np.array(list(w), 'U1')
        print(char_embedding)
        if (char_as_int)
        char_as_int = char_embedding.view(np.uint32)[:max_word_size]
        print(char_as_int)
        embedding_matrix[i] = np.array(char_as_int)
        i+=1
        


matrix = create_word_embedding(lexicon, 128)
        
        
        
    

['n' 'a' 'q' 'i' 'l' 'ç' 'u' 'h']
[110  97 113 105 108 231 117 104]


ValueError: could not broadcast input array from shape (8,) into shape (128,)